#! /usr/bin/perl
use strict;
use warnings;
use Carp::Always;
use lib 'editions/cli-sftp';
use CDS;

my $actor = CDS::CLIActor->openOrCreateDefault // exit(1);

for my $file (@ARGV) {
	$actor->ui->line($file);

}
