#! /bin/sh

sudo rm /usr/local/bin/condensation-*
sudo rm -r /usr/local/lib/x86_64-linux-gnu/perl/5.20.1/Condensation
sudo rm -r /usr/local/lib/x86_64-linux-gnu/perl/5.20.1/auto/Condensation
echo 'Done!'
