#! /usr/bin/perl
use strict;
use warnings;
use lib 'editions/cli';
use CDS;
use Carp::Always;
use ViereckFilter;

# Prepare
my $ui = CDS::UI->new;

# Clean
#system('cd module && make distclean');
system('rm', '-r', 'module/lib');
system('rm', '-r', 'module/scripts');

# Release the new library
mkdir 'module/lib', 0755;
&publishLibrary('editions/cli/CDS.pm', 'module/lib/CDS.pm', 0644);

sub publishLibrary($fromFile, $toFile, $mode) {
	my $content = CDS->readBytesFromFile($fromFile) // &fatalError('File "', $fromFile, '" not found.');
	CDS->writeBytesToFile($toFile, $content) // &fatalError('Unable to write "', $toFile, '".');
	chmod $mode, $toFile;
}

# Release the new script
mkdir 'module/scripts', 0755;
&publishScript('cds', 'module/scripts/cds', 0755);

sub publishScript($fromFile, $toFile, $mode) {
	my $content = CDS->readBytesFromFile($fromFile) // &fatalError('File "', $fromFile, '" not found.');
	$content =~ s/\nuse lib \'.*?\';//g;
	CDS->writeBytesToFile($toFile, $content) // &fatalError('Unable to write "', $toFile, '".');
	chmod $mode, $toFile;
}

# Update Makefile.PL
my $scripts = join ', ', sort map { '\'scripts/'.$_.'\'' } grep { -f 'module/scripts/'.$_ } CDS->listFolder('module/scripts');
my $content = CDS->readBytesFromFile('module/Makefile.PL');
$content =~ s/EXE_FILES\s*=>\s*\[.*?\]/EXE_FILES		=> [$scripts]/gs;
CDS->writeBytesToFile('module/Makefile.PL', $content) || die 'Unable to write module/Makefile.PL';

# Write the MANIFEST file
open(M, '>', 'module/MANIFEST');
print M 'Changes', "\n";
print M 'Makefile.PL', "\n";
print M 'MANIFEST', "\n";
print M 'README', "\n";
print M 't/Condensation.t', "\n";
close M;
system('cd module && find lib -name \'*.pm\' | sort >> MANIFEST');
system('cd module && find scripts -type f | sort >> MANIFEST');

# Warp up
$ui->line($ui->green('Module updated'));

sub fatalError {
	$ui->line($ui->red(@_));
	exit(1);
}
