#! /usr/bin/perl
use strict;
use warnings;
use lib '..';
use Digest::SHA;
use Condensation::C;

# CTR encryption / decryption
my $key = Condensation::C::randomBytes(32);
my $startCounter = Condensation::C::randomBytes(16);

print 'Key ', unpack('H*', $key), "\n";
print 'Counter (at start) ', unpack('H*', $startCounter), "\n";

my $plain = 'In cryptography, a cipher (or cypher) is an algorithm for performing encryption or decryption—a series of well-defined steps that can be followed as a procedure. An alternative, less common term is encipherment. To encipher or encode is to convert information from plain text into cipher or code. In non-technical usage, a cipher is the same thing as a code; however, the concepts are distinct in cryptography. In classical cryptography, ciphers were distinguished from codes.';
my $encrypted = Condensation::C::aesCrypt($plain, $key, $startCounter);
print 'Encrypted ', unpack('H*', $encrypted), "\n";
my $decrypted = Condensation::C::aesCrypt($encrypted, $key, $startCounter);
print 'Decrypted ', $decrypted, "\n";

# Key derivation
my $iv = Condensation::C::randomBytes(32);
my $derived = Condensation::C::aesKDF($key, $iv, 1000);
print 'IV ', unpack('H*', $iv), "\n";
print 'Derived key ', unpack('H*', $derived), "\n";
