# BEGIN AUTOGENERATED

sub register($class, $cds, $help) {
	my $node000 = CDS::Parser::Node->new(0);
	my $node001 = CDS::Parser::Node->new(0);
	my $node002 = CDS::Parser::Node->new(0);
	my $node003 = CDS::Parser::Node->new(0);
	my $node004 = CDS::Parser::Node->new(0);
	my $node005 = CDS::Parser::Node->new(1, {constructor => \&new, function => \&help});
	my $node006 = CDS::Parser::Node->new(0);
	my $node007 = CDS::Parser::Node->new(0);
	my $node008 = CDS::Parser::Node->new(0);
	my $node009 = CDS::Parser::Node->new(0);
	my $node010 = CDS::Parser::Node->new(1);
	my $node011 = CDS::Parser::Node->new(0);
	my $node012 = CDS::Parser::Node->new(0);
	my $node013 = CDS::Parser::Node->new(0);
	my $node014 = CDS::Parser::Node->new(0);
	my $node015 = CDS::Parser::Node->new(0);
	my $node016 = CDS::Parser::Node->new(1);
	my $node017 = CDS::Parser::Node->new(0);
	my $node018 = CDS::Parser::Node->new(0);
	my $node019 = CDS::Parser::Node->new(1, {constructor => \&new, function => \&get});
	my $node020 = CDS::Parser::Node->new(1);
	my $node021 = CDS::Parser::Node->new(0);
	my $node022 = CDS::Parser::Node->new(1, {constructor => \&new, function => \&get});
	$cds->addArrow($node000, 1, 0, 'get');
	$cds->addArrow($node001, 1, 0, 'save');
	$cds->addArrow($node002, 1, 0, 'get');
	$cds->addArrow($node003, 1, 0, 'get');
	$cds->addArrow($node009, 1, 0, 'save', \&collectSave);
	$help->addArrow($node005, 1, 0, 'get');
	$help->addArrow($node005, 1, 0, 'save');
	$node000->addArrow($node010, 1, 0, 'HASH', \&collectHash);
	$node001->addArrow($node004, 1, 0, 'data');
	$node002->addArrow($node006, 1, 0, 'HASH', \&collectHash1);
	$node003->addArrow($node010, 1, 0, 'OBJECT', \&collectObject);
	$node004->addArrow($node009, 1, 0, 'of', \&collectOf);
	$node006->addArrow($node007, 1, 0, 'on');
	$node006->addArrow($node008, 0, 0, 'from');
	$node007->addArrow($node010, 1, 0, 'STORE', \&collectStore);
	$node008->addArrow($node010, 0, 0, 'STORE', \&collectStore);
	$node009->addArrow($node013, 1, 0, 'HASH', \&collectHash1);
	$node009->addArrow($node016, 1, 0, 'HASH', \&collectHash);
	$node009->addArrow($node016, 1, 0, 'OBJECT', \&collectObject1);
	$node010->addArrow($node011, 1, 0, 'decrypted');
	$node010->addDefault($node019);
	$node011->addArrow($node012, 1, 0, 'with');
	$node012->addArrow($node019, 1, 0, 'AESKEY', \&collectAeskey);
	$node013->addArrow($node014, 1, 0, 'on');
	$node013->addArrow($node015, 0, 0, 'from');
	$node014->addArrow($node016, 1, 0, 'STORE', \&collectStore);
	$node015->addArrow($node016, 0, 0, 'STORE', \&collectStore);
	$node016->addArrow($node017, 1, 0, 'decrypted');
	$node016->addDefault($node020);
	$node017->addArrow($node018, 1, 0, 'with');
	$node018->addArrow($node020, 1, 0, 'AESKEY', \&collectAeskey);
	$node020->addArrow($node021, 1, 0, 'as');
	$node021->addArrow($node022, 1, 0, 'FILENAME', \&collectFilename);
}

sub collectAeskey($o, $label, $value) {
	$o:aesKey = $value;
}

sub collectFilename($o, $label, $value) {
	$o:filename = $value;
}

sub collectHash($o, $label, $value) {
	$o:hash = $value;
	$o:store = $o:actor->preferredStore;
}

sub collectHash1($o, $label, $value) {
	$o:hash = $value;
}

sub collectObject($o, $label, $value) {
	$o:hash = $value->hash;
	$o:store = $value->cliStore;
}

sub collectObject1($o, $label, $value) {
	$o:hash = $value->hash;
	push @$o:stores, $value->store;
}

sub collectOf($o, $label, $value) {
	$o:saveData = 1;
}

sub collectSave($o, $label, $value) {
	$o:saveObject = 1;
}

sub collectStore($o, $label, $value) {
	$o:store = $value;
}

sub new($class, $actor) { bless {actor => $actor, ui => $actor->ui} }

# END AUTOGENERATED

# HTML FOLDER NAME store-get
# HTML TITLE Get
sub help($o, $cmd) {
	my $ui = $o:ui;
	$ui->space;
	$ui->command('cds get OBJECT');
	$ui->command('cds get HASH on STORE');
	$ui->p('Downloads an object and writes it to STDOUT. If the object is not found, the program quits with exit code 1.');
	$ui->space;
	$ui->command('cds get HASH');
	$ui->p('As above, but uses the selected store.');
	$ui->space;
	$ui->command('… decrypted with AESKEY');
	$ui->p('Decrypts the object after retrieval.');
	$ui->space;
	$ui->command('cds save … as FILENAME');
	$ui->p('Saves the object to FILENAME instead of writing it to STDOUT.');
	$ui->space;
	$ui->command('cds save data of … as FILENAME');
	$ui->p('Saves the object\'s data to FILENAME.');
	$ui->space;
	$ui->title('Related commands');
	$ui->line('cds open envelope OBJECT');
	$ui->line('cds show record OBJECT [decrypted with AESKEY]');
	$ui->line('cds show hashes of OBJECT');
	$ui->space;
}

sub get($o, $cmd) {
	$cmd->collect($o);

	# Retrieve the object
	my $object = $o:actor->uiGetObject($o:hash, $o:store, $o:actor->preferredKeyPairToken) // return;

	# Decrypt
	$object = $object->crypt($o:aesKey) if defined $o:aesKey;

	# Output
	if ($o:saveData) {
		CDS->writeBytesToFile($o:filename, $object->data) // return $o:ui->error('Failed to write data to "', $o:filename, '".');
		$o:ui->pGreen(length $object->data, ' bytes written to ', $o:filename, '.');
	} elsif ($o:saveObject) {
		CDS->writeBytesToFile($o:filename, $object->bytes) // return $o:ui->error('Failed to write object to "', $o:filename, '".');
		$o:ui->pGreen(length $object->bytes, ' bytes written to ', $o:filename, '.');
	} else {
		$o:ui->raw($object->bytes);
	}
}
