#! /usr/bin/perl
use strict;
use warnings;
use Carp::Always;
use lib 'editions/cli-sftp';
use CDS;

my $ui = CDS::UI->new(*STDOUT);
my $actor = CDS::CLIActor->openOrCreateDefault($ui) // exit(1);

for my $file (@ARGV) {
	$actor->ui->line($file);
}

# Read the root
&traverse($actor->groupRoot);

sub traverse {
	my $selector = shift;
	$ui->pushIndent;

	for my $child ($selector->children) {
		$ui->line($ui->bold($child->label));

		$ui->pushIndent;
		$ui->record($child->record);
		$ui->popIndent;

		&traverse($child);
	}

	$ui->popIndent;
}

# Save any changes
#$actor->saveOrShowError;
