#! /usr/bin/perl

# This is the Condensation Perl Module 0.29 (cli) built on 2022-03-07.
# See https://condensation.io for information about the Condensation Data System.

use strict;
use warnings;
use CDS;

my $exitCode = CDS::CLI->run;
exit($exitCode);
