#! /usr/bin/perl
use strict;
use warnings;
use Carp::Always;

# Use the locally built CDS.pm with debug information.
use File::Basename;
use lib dirname(__FILE__).'/../editions/cli-debug';
use CDS;

my $exitCode = CDS::CLI->run;
exit($exitCode);
